[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Genome Cookbook"
authors = [{name = "Austin Osmanski", email = "aosmanski@hudsonalpha.org"}]
dynamic = ["version", "description"]
